// AUTH
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";


export const REFREASH_LOGIN = "REFREASH_LOGIN";
export const RESET_USER_DETAILS_SUCCESS = "RESET_USER_DETAILS_SUCCESS";

// Balance
export const FETCH_BALANCE_REQUEST = "FETCH_BALANCE_REQUEST";
export const FETCH_BALANCE_SUCCESS = "FETCH_BALANCE_SUCCESS";
export const FETCH_BALANCE_FAILURE = "FETCH_BALANCE_FAILURE";

// Search Event
export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";

//Deposit methods
export const FETCH_DEPOSIT_METHOD_REQUEST = "FETCH_DEPOSIT_METHOD_REQUEST";
export const FETCH_DEPOSIT_METHOD_SUCCESS = "FETCH_DEPOSIT_METHOD_SUCCESS";
export const FETCH_DEPOSIT_METHOD_FAILURE = "FETCH_DEPOSIT_METHOD_FAILURE";

//Deposit Details
export const FETCH_DEPOSIT_DETAILS_REQUEST = "FETCH_DEPOSIT_DETAILS_REQUEST";
export const FETCH_DEPOSIT_DETAILS_SUCCESS = "FETCH_DEPOSIT_DETAILS_SUCCESS";
export const FETCH_DEPOSIT_DETAILS_FAILURE = "FETCH_DEPOSIT_DETAILS_FAILURE";

//Withdrawls Details
export const FETCH_WITHDRAWALS_DETAILS_REQUEST = "FETCH_WITHDRAWALS_DETAILS_REQUEST";
export const FETCH_WITHDRAWALS_DETAILS_SUCCESS = "FETCH_WITHDRAWALS_DETAILS_SUCCESS";
export const FETCH_WITHDRAWALS_DETAILS_FAILURE = "FETCH_WITHDRAWALS_DETAILS_FAILURE";

// Transactions Details
export const FETCH_TRANSACTIONS_DETAILS_REQUEST = "FETCH_TRANSACTIONS_DETAILS_REQUEST";
export const FETCH_TRANSACTIONS_DETAILS_SUCCESS = "FETCH_TRANSACTIONS_DETAILS_SUCCESS";
export const FETCH_TRANSACTIONS_DETAILS_FAILURE = "FETCH_TRANSACTIONS_DETAILS_FAILURE";

// P&L Transactions Details
export const FETCH_PL_TRANSACTIONS_DETAILS_REQUEST = "FETCH_PL_TRANSACTIONS_DETAILS_REQUEST";
export const FETCH_PL_TRANSACTIONS_DETAILS_SUCCESS = "FETCH_PL_TRANSACTIONS_DETAILS_SUCCESS";
export const FETCH_PL_TRANSACTIONS_DETAILS_FAILURE = "FETCH_PL_TRANSACTIONS_DETAILS_FAILURE";

// Account Statement  Details
export const FETCH_ACCOUNT_STATEMENT_DETAILS_REQUEST = "FETCH_ACCOUNT_STATEMENT_DETAILS_REQUEST";
export const FETCH_ACCOUNT_STATEMENT_DETAILS_SUCCESS = "FETCH_ACCOUNT_STATEMENT_DETAILS_SUCCESS";
export const FETCH_ACCOUNT_STATEMENT_DETAILS_FAILURE = "FETCH_ACCOUNT_STATEMENT_DETAILS_FAILURE";

// Account Statement  Details
export const FETCH_MATCHED_DETAILS_REQUEST = "FETCH_MATCHED_DETAILS_REQUEST";
export const FETCH_MATCHED_DETAILS_SUCCESS = "FETCH_MATCHED_DETAILS_SUCCESS";
export const FETCH_MATCHED_DETAILS_FAILURE = "FETCH_MATCHED_DETAILS_FAILURE";

// Matched  Details
export const FETCH_UNMATCHED_DETAILS_REQUEST = "FETCH_UNMATCHED_DETAILS_REQUEST";
export const FETCH_UNMATCHED_DETAILS_SUCCESS = "FETCH_UNMATCHED_DETAILS_SUCCESS";
export const FETCH_UNMATCHED_DETAILS_FAILURE = "FETCH_UNMATCHED_DETAILS_FAILURE";

// UnMatched  Details
export const FETCH_MY_BETS_DETAILS_REQUEST = "FETCH_MY_BETS_DETAILS_REQUEST";
export const FETCH_MY_BETS_DETAILS_SUCCESS = "FETCH_MY_BETS_DETAILS_SUCCESS";
export const FETCH_MY_BETS_DETAILS_FAILURE = "FETCH_MY_BETS_DETAILS_FAILURE";

// Live score/run  Details
export const FETCH_SCORE_BY_MARKET_REQUEST = "FETCH_SCORE_BY_MARKET_REQUEST";
export const FETCH_SCORE_BY_MARKET_SUCCESS = "FETCH_SCORE_BY_MARKET_SUCCESS";
export const FETCH_SCORE_BY_MARKET_FAILURE = "FETCH_SCORE_BY_MARKET_FAILURE";

//Index
export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';

export const LOAD_TOASTER = 'LOAD_TOASTER';
